docs: Add sections 6 and 7 for Hazard Analysis
harshc22/ML-Herd-Management pull request #53
Opened 2024-10-25 00:03 UTC by KrishPatel27

Added sections 6 and 7 for the Hazard Analysis.

2024-10-25 16:58 UTC, harshc22 commented on docs/HazardAnalysis/HazardAnalysis.tex
> +    ensure that critical information, such as local breeding data, developed models, and so forth are not lost in case of system failure or crash. It should also
nit: more than 80 characters in this line

2024-10-25 16:58 UTC, harshc22 commented on docs/HazardAnalysis/HazardAnalysis.tex
> +inlcuded if there is extra time.
- typo 'included'
- also is there a way to make the timeline more specific? 
- This is what TA said in the meeting " exact dates not required, the sequence of events/milestones is more important/relevant, refer to dev plan if applicable"

2024-10-25 16:58 UTC, harshc22 commented on docs/HazardAnalysis/HazardAnalysis.tex
missing revision

2024-10-25 18:15 UTC, KrishPatel27 commented on docs/HazardAnalysis/HazardAnalysis.tex
> +inlcuded if there is extra time.
I can say that it correlates with the proof of concept demo plan (Section 8, Point 6 of the Development Plan).

2024-10-25 18:19 UTC, KrishPatel27 commented on docs/HazardAnalysis/HazardAnalysis.tex
Added

2024-10-25 21:48 UTC, ShazimR requested changes

2024-10-25 21:48 UTC, ShazimR commented on docs/HazardAnalysis/HazardAnalysis.tex
> +    to 10\%, but will likely to re-evaluated later. A warning or error message
This sentence is worded poorly, I suggest "This value is currently set to 10%, but will likely be re-evaluated later."

2024-10-25 21:48 UTC, ShazimR commented on docs/HazardAnalysis/HazardAnalysis.tex
> +    every 24 hours, witmah at least 99\% success in restoring data during tests.
nit: typo in "witmah"

2024-10-25 21:48 UTC, ShazimR commented on docs/HazardAnalysis/HazardAnalysis.tex
> +Demonstration. It will then be implemented when the system is being built.
I'm a little confused on what you are trying to say here "It will be abstractd added before...", although this is probably just a typo

2024-10-25 21:48 UTC, ShazimR commented on docs/HazardAnalysis/HazardAnalysis.tex
> +included if there is extra time. There is no timeline for these tasks.
Same as earlier, odd wording, I suggest "Other safety concerns are not of higher priority, thus they may be 
included if there is extra time."

2024-10-25 23:05 UTC, KrishPatel27 commented on docs/HazardAnalysis/HazardAnalysis.tex
> +Demonstration. It will then be implemented when the system is being built.
I was trying to say that we plan to include it in the model before we even start building it. ie. adding checks that the dam and sire are not related before we start building model.

2024-10-25 23:51 UTC, Aryanpatel335 submitted a review, later dismissed
Looks good to me

2024-10-25 23:53 UTC, ShazimR requested changes

2024-10-25 23:53 UTC, ShazimR commented on docs/HazardAnalysis/HazardAnalysis.tex
> +    coefficient above a set threshold is approved. This value can currently set
shouldn't this be "is currently set..."?

2024-10-26 00:21 UTC, ShazimR submitted a review, later dismissed
all comments were addressed, approved!

2024-10-26 00:40 UTC, ShazimR approved these changes

2024-10-26 00:40 UTC, merged